### ISSUE TITLE
Support for macOS < 10.12

### ISSUE THREAD

**Issue by macmade** [sindresorhus/CircularProgress#18]
Is there any reason the deployment target for the whole project is macOS 10.12?

Except the test app which uses a single call to a macOS 10.12 only API, it seems that the whole project builds and runs fine on macOS 10.10.

The test app uses `NSTimer.scheduledTimer`, passing a closure, but this could easily be replaced with the selector variant in order to support macOS 10.10.

**Comment by sindresorhus** [comment]
I only support what I can test on and I only have a VM back to 10.12. I also don't see the point in supporting such an old macOS version. While it looks like it works fine on 10.10, there might be problems discovered in the future or new features requiring newer system APIs, and I just don't want to spend my time fixing bugs caused by macOS versions I don't support in my own apps.

So in short, while it probably works in 10.10, I just don't want to deal with supporting it.

**Comment by macmade** [comment]
Fair enough, thanks for the answer : )
